version: "3"

services:
  database:
    container_name: data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    image: postgres:13.3
  security:
    build: security/
    ports:
      - "8090:8090"
    network_mode: host
    depends_on:
      - database
  stockmarkets:
    build: stockmarkets/
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - security